In [64]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
# import warnings
# warnings.filterwarnings('ignore')



In [66]:
ds=pd.read_csv('startup_data.csv')
ds

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [67]:
ds.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [68]:
#diving into dependent and independent:
x=ds[['R&D Spend','Administration','Marketing Spend','State']]
y=ds[['Profit']]

In [73]:
#encoded state column using onehotencoder:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
encoded_data=ohe.fit_transform(x[['State']])
encoded_data

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [70]:
# import matplotlib.pyplot as plt

In [74]:
column_name=ohe.get_feature_names_out(['State'])
encoded_df=pd.DataFrame(encoded_data,columns=column_name)
encoded_df

State_California  State_Florida  State_New York
0                0.0            0.0             1.0
1                1.0            0.0             0.0
2                0.0            1.0             0.0
3                0.0            0.0             1.0
4                0.0            1.0             0.0
5                0.0            0.0             1.0
6                1.0            0.0             0.0
7                0.0            1.0             0.0
8                0.0            0.0             1.0
9                1.0            0.0             0.0
10               0.0            1.0             0.0
11               1.0            0.0             0.0
12               0.0            1.0             0.0
13               1.0            0.0             0.0
14               0.0            1.0             0.0
15               0.0            0.0             1.0
16               1.0            0.0             0.0
17               0.0            0.0             1.0
18               0.0            1.0             0.0
19               0.0            0.0             1.0
20               1.0            0.0             0.0
21               0.0            0.0             1.0
22               0.0            1.0             0.0
23               0.0            1.0             0.0
24               0.0            0.0             1.0
25               1.0            0.0             0.0
26               0.0            1.0             0.0
27               0.0            0.0             1.0
28               0.0            1.0             0.0
29               0.0            0.0             1.0
30               0.0            1.0             0.0
31               0.0            0.0             1.0
32               1.0            0.0             0.0
33               0.0            1.0             0.0
34               1.0            0.0             0.0
35               0.0            0.0             1.0
36               0.0            1.0             0.0
37               1.0            0.0             0.0
38               0.0            0.0             1.0
39               1.0            0.0             0.0
40               1.0            0.0             0.0
41               0.0            1.0             0.0
42               1.0            0.0             0.0
43               0.0            0.0             1.0
44               1.0            0.0             0.0
45               0.0            0.0             1.0
46               0.0            1.0             0.0
47               1.0            0.0             0.0
48               0.0            0.0             1.0
49               1.0            0.0             0.0

In [79]:
#joined x(independed data variable)and encoded dataframe:
x=pd.concat([x,encoded_df],axis=1)
x=x.drop(columns=['State'])
x

R&D Spend  Administration  Marketing Spend  State_California  \
0   165349.20       136897.80        471784.10               0.0   
1   162597.70       151377.59        443898.53               1.0   
2   153441.51       101145.55        407934.54               0.0   
3   144372.41       118671.85        383199.62               0.0   
4   142107.34        91391.77        366168.42               0.0   
5   131876.90        99814.71        362861.36               0.0   
6   134615.46       147198.87        127716.82               1.0   
7   130298.13       145530.06        323876.68               0.0   
8   120542.52       148718.95        311613.29               0.0   
9   123334.88       108679.17        304981.62               1.0   
10  101913.08       110594.11        229160.95               0.0   
11  100671.96        91790.61        249744.55               1.0   
12   93863.75       127320.38        249839.44               0.0   
13   91992.39       135495.07        252664.93               1.0   
14  119943.24       156547.42        256512.92               0.0   
15  114523.61       122616.84        261776.23               0.0   
16   78013.11       121597.55        264346.06               1.0   
17   94657.16       145077.58        282574.31               0.0   
18   91749.16       114175.79        294919.57               0.0   
19   86419.70       153514.11             0.00               0.0   
20   76253.86       113867.30        298664.47               1.0   
21   78389.47       153773.43        299737.29               0.0   
22   73994.56       122782.75        303319.26               0.0   
23   67532.53       105751.03        304768.73               0.0   
24   77044.01        99281.34        140574.81               0.0   
25   64664.71       139553.16        137962.62               1.0   
26   75328.87       144135.98        134050.07               0.0   
27   72107.60       127864.55        353183.81               0.0   
28   66051.52       182645.56        118148.20               0.0   
29   65605.48       153032.06        107138.38               0.0   
30   61994.48       115641.28         91131.24               0.0   
31   61136.38       152701.92         88218.23               0.0   
32   63408.86       129219.61         46085.25               1.0   
33   55493.95       103057.49        214634.81               0.0   
34   46426.07       157693.92        210797.67               1.0   
35   46014.02        85047.44        205517.64               0.0   
36   28663.76       127056.21        201126.82               0.0   
37   44069.95        51283.14        197029.42               1.0   
38   20229.59        65947.93        185265.10               0.0   
39   38558.51        82982.09        174999.30               1.0   
40   28754.33       118546.05        172795.67               1.0   
41   27892.92        84710.77        164470.71               0.0   
42   23640.93        96189.63        148001.11               1.0   
43   15505.73       127382.30         35534.17               0.0   
44   22177.74       154806.14         28334.72               1.0   
45    1000.23       124153.04          1903.93               0.0   
46    1315.46       115816.21        297114.46               0.0   
47       0.00       135426.92             0.00               1.0   
48     542.05        51743.15             0.00               0.0   
49       0.00       116983.80         45173.06               1.0   

    State_Florida  State_New York  State_California  State_Florida  \
0             0.0             1.0               0.0            0.0   
1             0.0             0.0               1.0            0.0   
2             1.0             0.0               0.0            1.0   
3             0.0             1.0               0.0            0.0   
4             1.0             0.0               0.0            1.0   
5             0.0             1.0               0.0            0.0   
6             0.0             0.0            

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=5,random_state=0)
x_test

R&D Spend  Administration  Marketing Spend  State_California  \
28   66051.52       182645.56        118148.20               0.0   
11  100671.96        91790.61        249744.55               1.0   
10  101913.08       110594.11        229160.95               0.0   
41   27892.92        84710.77        164470.71               0.0   
2   153441.51       101145.55        407934.54               0.0   

    State_Florida  State_New York  State_California  State_Florida  \
28            1.0             0.0               0.0            1.0   
11            0.0             0.0               1.0            0.0   
10            1.0             0.0               0.0            1.0   
41            1.0             0.0               0.0            1.0   
2             1.0             0.0               0.0            1.0   

    State_New York  
28             0.0  
11             0.0  
10             0.0  
41             0.0  
2              0.0

In [82]:
#let train model:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [83]:
reg.coef_

array([[ 7.78395354e-01,  5.70695437e-03,  3.21344322e-02,
         6.24251382e+01, -5.14178160e+02,  4.51753021e+02,
         6.24251382e+01, -5.14178160e+02,  4.51753021e+02]])

In [84]:
reg.intercept_

array([46250.73721998])

In [92]:
data=[[165349.20, 136897.80, 471784.10, 0, 0, 1]]
columns=x.columns
myinput=pd.DataFrame(column=columns,data=data)
result=reg.predict(myinput)
result

TypeError: DataFrame.__init__() got an unexpected keyword argument 'column'. Did you mean 'columns'?

In [ ]:
y_pred=reg.predict(x_test)
y_pred

In [ ]:
y_test

In [ ]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
score